// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozkdgthtwctfdcthgtxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96a2RndGh0d2N0ZmRjdGhndHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNzM0MTYsImV4cCI6MjA1Nzk0OTQxNn0.0UndGBLiQmFTTSvrGQL-pNecVJSzNBYFpoLLGvwKkqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});